#!/bin/bash

if [ $(uname -p) != "x86_64" ]; then
 echo "This test only runs on x86_64 host"
 exit 1
fi

unset SWTPM

# FIXME:
# Due to some bug in glib2 for i686 we don't seem to be able to run a
# 32bit swtpm with cuse interface correctly. The g_cond_wait_until()
# doesn't behave as it does with 64bit. test_hashing2 gets stuck.


CFLAGS='-m64' ./configure --with-openssl --with-gnutls --prefix=/usr --libdir=/lib64 && \
 make clean && \
 make -j$(nproc) &&
 sudo make -j$(nproc) install &&
 cp /usr/bin/swtpm /tmp/swtpm64 &&
 make -j$(nproc) check &&
 sudo make -j$(nproc) check ||
 exit 1

PKG_CONFIG_PATH=/usr/lib/pkgconfig \
 CFLAGS='-m32' ./configure --with-openssl --with-gnutls --prefix=/usr --libdir=/lib && \
 make clean && \
 make -j$(nproc) &&
 sudo make -j$(nproc) install &&
 cp /usr/bin/swtpm /tmp/swtpm32 &&
 make -j$(nproc) check &&
 SWTPM_EXE=/tmp/swtpm64 make -j$(nproc) check &&
 sudo SWTPM_EXE=/tmp/swtpm64 make -j$(nproc) check ||
 exit 1

CFLAGS='-m64' ./configure --with-openssl --with-gnutls --prefix=/usr --libdir=/lib64 && \
 make clean && \
 make -j$(nproc) &&
 SWTPM_EXE=/tmp/swtpm32 make -j$(nproc) check &&
 exit 1
