#!/usr/bin/env bash

TESTDIR=${abs_top_testdir:-$(dirname "$0")}
ROOT=${abs_top_builddir:-$(dirname "$0")/..}
source "${TESTDIR}/common"
skip_test_no_tpm20 "${SWTPM_EXE}"

cd "$(dirname "$0")" || exit 1

export SWTPM_IFACE=cuse
bash _test_tpm2_print_states
ret=$?
[ $ret -ne 0 ] && [ $ret -ne 77 ] && exit $ret

export SWTPM_IFACE=socket
export SWTPM_INTERFACE=socket+socket
export SWTPM_SERVER_NAME=localhost
export SWTPM_SERVER_PORT=65470
export SWTPM_CTRL_PORT=65471
bash _test_tpm2_print_states
ret=$?
[ $ret -ne 0 ] && [ $ret -ne 77 ] && exit $ret

if test_swtpm_has_chardev "${SWTPM_EXE}"; then
	export SWTPM_IFACE=chardev
	bash _test_tpm2_print_states
	ret=$?
	[ $ret -ne 0 ] && [ $ret -ne 77 ] && exit $ret
else
	echo "Skip: No chardev available"
fi

exit 0
